// Les envies demandées à l'inscription, une étape par catégorie (voir docs/decisions.md).
// « alcool » : masqué entre 15 et 17 ans (AGE_ALCOOL). « sensible » : peut révéler une religion ou la santé (RGPD, article 9).
import type { CategorieEnvie } from "@sos-miam/commun/types/profil";

export type ChoixEnvie = {
  id: string;
  libelle: string;
  emoji: string;
  alcool?: boolean;
  sensible?: boolean;
};

export type EtapeEnvies = {
  categorie: CategorieEnvie;
  /** Nom court de la catégorie (écran Profil) */
  nom: string;
  emoji: string;
  titre: string;
  sousTitre: string;
  /** Toute l'étape est masquée aux moins de 18 ans */
  alcool?: boolean;
  /** Mention affichée sous les choix */
  note?: string;
  choix: ChoixEnvie[];
};

export const etapesEnvies: EtapeEnvies[] = [
  {
    categorie: "lieux",
    nom: "Lieux",
    emoji: "🍽️",
    titre: "Tu sors où ?",
    sousTitre: "Choisis tout ce qui te tente, on s'occupe du reste.",
    choix: [
      { id: "restos", libelle: "Restos", emoji: "🍝" },
      { id: "patisseries", libelle: "Pâtisseries et boulangeries", emoji: "🥐" },
      { id: "cafes", libelle: "Cafés", emoji: "☕" },
      { id: "bars", libelle: "Bars", emoji: "🍹", alcool: true },
      { id: "glaciers", libelle: "Glaciers", emoji: "🍦" },
      { id: "food-trucks", libelle: "Food trucks", emoji: "🚚" },
      { id: "salons-de-the", libelle: "Salons de thé", emoji: "🫖" },
      { id: "halles", libelle: "Halles et marchés", emoji: "🧺" },
      { id: "caves", libelle: "Caves à vin", emoji: "🍷", alcool: true },
      { id: "plages", libelle: "Plages et paillotes", emoji: "🏖️" },
      { id: "guinguettes", libelle: "Guinguettes", emoji: "🪗" },
      { id: "cinemas", libelle: "Cinémas", emoji: "🎬" },
      { id: "concerts", libelle: "Concerts et événements", emoji: "🎤" },
      { id: "spectacles", libelle: "Spectacles et stand-up", emoji: "🎭" },
      { id: "musees", libelle: "Musées et expos", emoji: "🖼️" },
      { id: "bowlings", libelle: "Bowlings", emoji: "🎳" },
      { id: "escape-games", libelle: "Escape games", emoji: "🗝️" },
      { id: "ateliers", libelle: "Ateliers", emoji: "🎨" },
      { id: "loisirs-sportifs", libelle: "Escalade, padel et cie", emoji: "🧗" },
      { id: "nature", libelle: "Sorties nature", emoji: "🛶" },
      { id: "balades-mer", libelle: "Balades en mer", emoji: "⛵" },
      { id: "domaines", libelle: "Dégustations au domaine", emoji: "🍇", alcool: true },
      { id: "cafes-librairies", libelle: "Cafés-librairies", emoji: "📚" },
    ],
  },
  {
    categorie: "cuisines",
    nom: "Cuisines",
    emoji: "🍝",
    titre: "Qu'est-ce qui te fait saliver ?",
    sousTitre: "Coche tout ce qui te met l'eau à la bouche.",
    choix: [
      { id: "italien", libelle: "Italien et pizzas", emoji: "🍕" },
      { id: "burger", libelle: "Burgers", emoji: "🍔" },
      { id: "bistrot", libelle: "Bistrot à la française", emoji: "🥖" },
      { id: "asiatique", libelle: "Asiatique", emoji: "🥢" },
      { id: "japonais", libelle: "Japonais et sushis", emoji: "🍣" },
      { id: "street-food", libelle: "Street food", emoji: "🌯" },
      { id: "fruits-de-mer", libelle: "Fruits de mer", emoji: "🦪" },
      { id: "poisson", libelle: "Poisson frais", emoji: "🎣" },
      { id: "local", libelle: "Spécialités d'ici", emoji: "🐙" },
      { id: "grillades", libelle: "Viandes et grillades", emoji: "🥩" },
      { id: "brunch", libelle: "Brunch", emoji: "🥞" },
      { id: "sucre", libelle: "Sucré", emoji: "🍰" },
      { id: "crepes", libelle: "Crêpes et galettes", emoji: "🫓" },
      { id: "maghrebin", libelle: "Couscous et tajines", emoji: "🍲" },
      { id: "libanais", libelle: "Libanais et mezzés", emoji: "🧆" },
      { id: "indien", libelle: "Indien", emoji: "🍛" },
      { id: "thai-vietnamien", libelle: "Thaï et vietnamien", emoji: "🍜" },
      { id: "mexicain", libelle: "Mexicain et latino", emoji: "🌮" },
      { id: "tapas", libelle: "Tapas et planches", emoji: "🫒" },
      { id: "poke", libelle: "Poké et salades", emoji: "🥗" },
      { id: "africain-antillais", libelle: "Africain et antillais", emoji: "🥘" },
      { id: "fromage", libelle: "Fromage qui file", emoji: "🧀" },
      { id: "gastronomique", libelle: "Gastronomique", emoji: "✨" },
      { id: "monde", libelle: "Cuisines du monde", emoji: "🌍" },
    ],
  },
  {
    categorie: "boissons",
    nom: "Boissons",
    emoji: "🍹",
    titre: "Et pour boire ?",
    sousTitre: "Avec ou sans alcool, tout se défend.",
    choix: [
      { id: "cocktails", libelle: "Cocktails", emoji: "🍸", alcool: true },
      { id: "vins", libelle: "Vins (nature aussi)", emoji: "🍷", alcool: true },
      { id: "bieres", libelle: "Bières artisanales", emoji: "🍺", alcool: true },
      { id: "apero", libelle: "Apéro et spritz", emoji: "🥂", alcool: true },
      { id: "cafes-specialite", libelle: "Cafés de spécialité", emoji: "☕" },
      { id: "thes", libelle: "Thés et bubble tea", emoji: "🧋" },
      { id: "jus", libelle: "Jus et smoothies", emoji: "🥤" },
      { id: "sans-alcool", libelle: "Sans alcool et mocktails", emoji: "🍹" },
      { id: "vin-rose", libelle: "Rosé bien frais", emoji: "🌸", alcool: true },
      { id: "bulles", libelle: "Champagne et bulles", emoji: "🍾", alcool: true },
      { id: "chocolat-chaud", libelle: "Chocolat chaud", emoji: "🍫" },
      { id: "limonades", libelle: "Limonades artisanales", emoji: "🍋" },
      { id: "matcha", libelle: "Matcha et chaï latte", emoji: "🍵" },
      { id: "milkshakes", libelle: "Milkshakes", emoji: "🍦" },
      { id: "pastis", libelle: "Pastis et anisés", emoji: "☀️", alcool: true },
      { id: "vins-du-coin", libelle: "Vins du coin (Languedoc)", emoji: "📍", alcool: true },
      { id: "whisky", libelle: "Whisky et spiritueux", emoji: "🥃", alcool: true },
      { id: "rhum", libelle: "Rhum et ti-punch", emoji: "🏝️", alcool: true },
      { id: "cidres", libelle: "Cidres et poirés", emoji: "🍎", alcool: true },
      { id: "diabolos", libelle: "Diabolos et sirops", emoji: "🍃" },
      { id: "kombucha", libelle: "Kombucha et kéfir", emoji: "🫙" },
      { id: "bieres-sans-alcool", libelle: "Bières et vins sans alcool", emoji: "🍻", alcool: true },
      { id: "digestifs", libelle: "Digestifs et liqueurs", emoji: "🍐", alcool: true },
      { id: "muscats", libelle: "Muscats et vins doux", emoji: "🍇", alcool: true },
    ],
  },
  {
    categorie: "bars",
    nom: "Bars",
    emoji: "🍻",
    titre: "Ton bar idéal ?",
    sousTitre: "Pour l'apéro, la soirée ou le dernier verre.",
    alcool: true,
    choix: [
      { id: "bar-cocktails", libelle: "Bar à cocktails", emoji: "🍸", alcool: true },
      { id: "bar-vin", libelle: "Bar à vin", emoji: "🍷", alcool: true },
      { id: "pub", libelle: "Pub", emoji: "🍺", alcool: true },
      { id: "bar-bieres", libelle: "Bar à bières", emoji: "🍻", alcool: true },
      { id: "rooftop", libelle: "Rooftop et terrasse", emoji: "🌇", alcool: true },
      { id: "cafe-quartier", libelle: "Café de quartier", emoji: "🏘️", alcool: true },
      { id: "bar-tapas", libelle: "Bar à tapas", emoji: "🫒", alcool: true },
      { id: "bar-concert", libelle: "Bar concert", emoji: "🎸", alcool: true },
      { id: "bar-match", libelle: "Bar à matchs (foot, rugby…)", emoji: "📺", alcool: true },
      { id: "bar-dansant", libelle: "Bar dansant", emoji: "🪩", alcool: true },
      { id: "bar-jeux", libelle: "Bar à jeux", emoji: "🎲", alcool: true },
      { id: "bar-de-nuit", libelle: "Bar ouvert tard", emoji: "🦉", alcool: true },
      { id: "bar-chic", libelle: "Bar chic et lounge", emoji: "🛋️", alcool: true },
      { id: "bar-secret", libelle: "Bar caché (speakeasy)", emoji: "🕵️", alcool: true },
      { id: "bar-associatif", libelle: "Bar associatif", emoji: "🤝", alcool: true },
      { id: "bar-huitres", libelle: "Bar à huîtres et picpoul", emoji: "🦪", alcool: true },
      { id: "bar-peniche", libelle: "Péniche et bar sur l'eau", emoji: "⚓", alcool: true },
      { id: "bar-rhum", libelle: "Bar à rhums arrangés", emoji: "🍍", alcool: true },
    ],
  },
  {
    categorie: "musique",
    nom: "Musique",
    emoji: "🎶",
    titre: "Côté musique ?",
    sousTitre: "L'ambiance qui te fait rester, ou danser.",
    choix: [
      { id: "pop", libelle: "Pop", emoji: "🎵" },
      { id: "rap", libelle: "Rap et hip-hop", emoji: "🎤" },
      { id: "electro", libelle: "Électro", emoji: "🎧" },
      { id: "rock", libelle: "Rock", emoji: "🎸" },
      { id: "live", libelle: "Concerts live", emoji: "🎙️" },
      { id: "chanson", libelle: "Chanson française", emoji: "🇫🇷" },
      { id: "calme", libelle: "Pas trop fort", emoji: "🤫" },
      { id: "rnb", libelle: "R&B", emoji: "💜" },
      { id: "latino", libelle: "Latino", emoji: "💃" },
      { id: "tubes-retro", libelle: "Tubes des années 80 à 2000", emoji: "📼" },
      { id: "funk-disco", libelle: "Funk et disco", emoji: "🕺" },
      { id: "jazz", libelle: "Jazz et soul", emoji: "🎷" },
      { id: "reggae", libelle: "Reggae", emoji: "🌴" },
      { id: "reggaeton", libelle: "Reggaeton", emoji: "🔥" },
      { id: "afro", libelle: "Afro et amapiano", emoji: "🥁" },
      { id: "house", libelle: "House", emoji: "🏠" },
      { id: "techno", libelle: "Techno", emoji: "🔊" },
      { id: "dj-set", libelle: "DJ set", emoji: "🎛️" },
      { id: "inde-folk", libelle: "Indé et folk", emoji: "🪕" },
      { id: "metal", libelle: "Métal", emoji: "🤘" },
      { id: "musique-classique", libelle: "Classique et opéra", emoji: "🎻" },
      { id: "rai-oriental", libelle: "Raï et oriental", emoji: "🪘" },
      { id: "scene-ouverte", libelle: "Jam et scène ouverte", emoji: "🎹" },
      { id: "bandas", libelle: "Bandas et peñas", emoji: "🎺" },
      { id: "rumba-flamenco", libelle: "Rumba catalane et flamenco", emoji: "🌹" },
    ],
  },
  {
    categorie: "jeux",
    nom: "Jeux et activités",
    emoji: "🎲",
    titre: "On joue ?",
    sousTitre: "De quoi te décoller du canapé, en solo ou en bande.",
    choix: [
      { id: "quiz", libelle: "Quiz", emoji: "❓" },
      { id: "jeux-societe", libelle: "Jeux de société", emoji: "🎲" },
      { id: "blind-test", libelle: "Blind test", emoji: "🎶" },
      { id: "karaoke", libelle: "Karaoké", emoji: "🎤" },
      { id: "bowling", libelle: "Bowling", emoji: "🎳" },
      { id: "billard", libelle: "Billard", emoji: "🎱" },
      { id: "flechettes", libelle: "Fléchettes", emoji: "🎯" },
      { id: "baby-foot", libelle: "Baby-foot", emoji: "⚽" },
      { id: "petanque", libelle: "Pétanque", emoji: "⚪" },
      { id: "escape-game", libelle: "Escape game", emoji: "🗝️" },
      { id: "laser-game", libelle: "Laser game", emoji: "🔫" },
      { id: "mini-golf", libelle: "Mini-golf", emoji: "⛳" },
      { id: "arcade", libelle: "Arcade et rétrogaming", emoji: "🕹️" },
      { id: "karting", libelle: "Karting", emoji: "🏎️" },
      { id: "accrobranche", libelle: "Accrobranche", emoji: "🌳" },
      { id: "ping-pong", libelle: "Ping-pong", emoji: "🏓" },
      { id: "molkky", libelle: "Mölkky", emoji: "🪵" },
      { id: "beach-volley", libelle: "Beach-volley", emoji: "🏐" },
      { id: "realite-virtuelle", libelle: "Réalité virtuelle", emoji: "🥽" },
      { id: "cours-danse", libelle: "Cours de danse", emoji: "💃" },
      { id: "ateliers-cuisine", libelle: "Ateliers cuisine", emoji: "🧑‍🍳" },
      { id: "murder-party", libelle: "Murder party", emoji: "🕵️" },
      { id: "jeux-de-role", libelle: "Jeux de rôle", emoji: "🐉" },
      { id: "joutes-nautiques", libelle: "Joutes nautiques", emoji: "🚣" },
    ],
  },
  {
    categorie: "moments",
    nom: "Moments",
    emoji: "💛",
    titre: "Tu sors plutôt…",
    sousTitre: "Avec qui, quand, comment : on te trouve le bon lieu au bon moment.",
    choix: [
      { id: "potes", libelle: "Entre potes", emoji: "🧑‍🤝‍🧑" },
      { id: "amoureux", libelle: "En amoureux", emoji: "💕" },
      { id: "famille", libelle: "En famille", emoji: "👨‍👩‍👧" },
      { id: "en-terrasse", libelle: "En terrasse", emoji: "☀️" },
      { id: "pause-dejeuner", libelle: "À la pause déj", emoji: "🕛" },
      { id: "sur-le-pouce", libelle: "Sur le pouce", emoji: "🥪" },
      { id: "petit-budget", libelle: "Petit budget", emoji: "🪙" },
      { id: "festif", libelle: "Festif", emoji: "🎉" },
      { id: "au-calme", libelle: "Au calme", emoji: "🌿" },
      { id: "solo", libelle: "En solo", emoji: "🎧" },
      { id: "apres-le-boulot", libelle: "Afterwork", emoji: "🌆", alcool: true },
      { id: "tard-le-soir", libelle: "Tard le soir", emoji: "🦉" },
      { id: "anniversaire", libelle: "Pour un anniversaire", emoji: "🎂" },
      { id: "gouter", libelle: "À l'heure du goûter", emoji: "🧁" },
      { id: "le-dimanche", libelle: "Le dimanche", emoji: "🛋️" },
      { id: "premier-rendez-vous", libelle: "Premier rendez-vous", emoji: "💘" },
      { id: "avec-les-enfants", libelle: "Avec les enfants", emoji: "🧸" },
      { id: "grande-tablee", libelle: "En grande tablée", emoji: "🍽️" },
      { id: "entre-collegues", libelle: "Entre collègues", emoji: "💼" },
      { id: "coucher-de-soleil", libelle: "Au coucher du soleil", emoji: "🌅" },
      { id: "pour-bosser", libelle: "Pour bosser ou réviser", emoji: "💻" },
      { id: "apres-les-cours", libelle: "Après les cours", emoji: "🎒" },
      { id: "avec-mon-chien", libelle: "Avec mon chien", emoji: "🐶" },
      { id: "grande-occasion", libelle: "Pour une grande occasion", emoji: "🌟" },
      { id: "faire-visiter", libelle: "Pour faire visiter le coin", emoji: "🗺️" },
    ],
  },
  {
    categorie: "regimes",
    nom: "Régime particulier",
    emoji: "🥗",
    titre: "Un régime particulier ?",
    sousTitre: "Facultatif : pour te montrer les lieux qui te conviennent.",
    note: "Ces choix restent sur ton téléphone et servent seulement à te proposer des lieux adaptés. Tu peux les changer ou les effacer quand tu veux.",
    choix: [
      { id: "vegetarien", libelle: "Végétarien", emoji: "🥕" },
      { id: "flexitarien", libelle: "Flexitarien", emoji: "🥦" },
      { id: "vegan", libelle: "Vegan", emoji: "🌱" },
      { id: "pescetarien", libelle: "Pescétarien", emoji: "🐟" },
      { id: "sans-gluten", libelle: "Sans gluten", emoji: "🌾", sensible: true },
      { id: "sans-lactose", libelle: "Sans lait ni lactose", emoji: "🥛", sensible: true },
      { id: "sans-porc", libelle: "Sans porc", emoji: "🐖", sensible: true },
      { id: "halal", libelle: "Halal", emoji: "🌙", sensible: true },
      { id: "casher", libelle: "Casher", emoji: "✡️", sensible: true },
      { id: "sans-boeuf", libelle: "Sans bœuf", emoji: "🐄", sensible: true },
      { id: "sans-sucre-ajoute", libelle: "Sans sucre ajouté", emoji: "🍬", sensible: true },
      { id: "sans-sel-ajoute", libelle: "Sans sel ajouté", emoji: "🧂", sensible: true },
      { id: "sans-cru", libelle: "Rien de cru", emoji: "🍣", sensible: true },
      { id: "allergie-arachides", libelle: "Allergie aux arachides", emoji: "🥜", sensible: true },
      { id: "allergie-fruits-a-coque", libelle: "Allergie aux fruits à coque", emoji: "🌰", sensible: true },
      { id: "allergie-oeufs", libelle: "Allergie aux œufs", emoji: "🥚", sensible: true },
      { id: "allergie-fruits-de-mer", libelle: "Allergie aux fruits de mer", emoji: "🦐", sensible: true },
      { id: "allergie-poisson", libelle: "Allergie au poisson", emoji: "🐠", sensible: true },
      { id: "allergie-sesame", libelle: "Allergie au sésame", emoji: "🥯", sensible: true },
      { id: "allergie-soja", libelle: "Allergie au soja", emoji: "🫘", sensible: true },
      { id: "allergie-moutarde", libelle: "Allergie à la moutarde", emoji: "🌭", sensible: true },
      { id: "allergie-celeri", libelle: "Allergie au céleri", emoji: "🥬", sensible: true },
      { id: "allergie-sulfites", libelle: "Allergie aux sulfites", emoji: "🍇", sensible: true },
      { id: "allergie-lupin", libelle: "Allergie au lupin", emoji: "🌼", sensible: true },
    ],
  },
];
