// Politique de confidentialité, section « Ton compte ambassadeur » (article 13 du RGPD), reprise par confidentialite.ts.
// Ce qui est vraiment gardé : modèles Compte, Ambassadeur, SessionCompte, BadgeCompte, JournalPoints, CandidatureFondateur,
// MissionAmbassadeur, MessageAmbassadeur, LectureMessage et DemandeLieu.compteId (apps/api/prisma/schema/comptes.prisma,
// ambassadeurs.prisma et gestion.prisma pour DemandeLieu). Le journal des mails (EnvoiCourriel, courriels.prisma) n'est
// pas relié au compte : adresse, type et objet du mail y restent 90 jours, même après la suppression du compte.
// Vérification de l'e-mail (Compte.emailVerifieLe, jetonVerification : empreinte, 7 jours) et « Mot de passe oublié » en
// libre-service (jetonReinitialisation : empreinte, 24 h) : décidés le 9 octobre 2026. Candidature fondateur : commune
// déclarée (communeCode), zone (zoneCode), numéros (numeroLocal, numeroNational), statut « souvenir » après un déménagement
// (docs/decisions.md, « Fondateurs par ville »).
// Ambassadeur certifié (docs/decisions.md, « Ambassadeur certifié ») : colonnes certifie_le, profil_certifie et structure
// sur ambassadeurs, et table candidatures_certification (profil, structure, commune, aide, envies, engagement, statut,
// dates) ; refusée, elle est effacée 3 mois après la réponse (ménage de nuit de l'API).
// La date de naissance n'est jamais gardée. Durées et limites d'essais : docs/decisions.md, « Espace ambassadeur ».
// « Déniché par » : le prénom est recopié sur la fiche du lieu accepté (Lieu.decouvertPar) ; il y reste si le compte est
// supprimé ou si le prénom change, d'où la promesse de le changer ou de le retirer sur simple demande.
import { adresseEspaceAmbassadeur } from "~/contenus/ambassadeurs";
import { hebergeur } from "~/contenus/legal/informations-legales";
import type { SectionLegale } from "~/contenus/legal/type-legal";

const lienEspace = `[${adresseEspaceAmbassadeur.replace("https://", "")}](${adresseEspaceAmbassadeur})`;

export const sectionCompteAmbassadeur: SectionLegale = {
  id: "compte-ambassadeur",
  titre: "Ton compte ambassadeur",
  blocs: [
    `Sur ${lienEspace}, tu peux créer un compte pour rejoindre le programme Ambassadeurs, **dès 18 ans**. L'équipe de SOS Miam (aujourd'hui, l'éditeur) regarde chaque inscription à la main ; une fois la tienne validée, ton espace s'ouvre : kit média, lieux à proposer, candidatures pour devenir fondateur ou ambassadeur certifié, missions et messages de l'équipe.`,
    {
      liste: [
        "**Ce qu'on garde sur ton compte** : ton adresse e-mail ; ton prénom ou ton surnom ; ta ville et, si tu le donnes, ton quartier ; l'**empreinte** de ton mot de passe (un code calculé à partir de lui, qui ne permet pas de le retrouver : ton mot de passe lui-même n'est jamais enregistré) ; la date de création du compte et la version des conditions d'utilisation que tu as acceptées ; si ton adresse e-mail est confirmée, et quand ; ton statut (en attente, validé, refusé ou suspendu) et la date de cette décision ; la date de ta dernière visite dans ton espace.",
        "**Ce que tu fais dans ton espace** : tes points, ton niveau et tes badges, avec l'historique de tes points (combien, quand et pourquoi) ; ta candidature pour devenir fondateur, si tu en envoies une (la commune où tu vis, que tu nous déclares, et la ville ou le département pour lequel tu candidates ; tes pépites, tes envies, tes réseaux si tu les donnes, pourquoi toi, si tu es partant pour la visio des fondateurs, comment tu as connu SOS Miam, et notre réponse) ; si tu deviens fondateur, tes numéros de fondateur (dans ta ville ou ton département, et en France), qui ne sont jamais redonnés à quelqu'un d'autre, même si tu déménages : ton titre reste alors en souvenir, et ta place se libère ; ta candidature pour devenir ambassadeur certifié, si tu en envoies une (si tu es plutôt ambassadeur, pro ou structure, le nom de ta structure ou de ton lieu si tu le donnes, la commune où tu vis, comment tu aides déjà les lieux, ce que tu aimerais faire, la case « jamais payé par un lieu » cochée, la date d'envoi, et notre réponse avec sa date) ; si tu deviens ambassadeur certifié, la date et le profil de ce titre, et ta structure ; les lieux que tu nous proposes ; les missions et les messages que l'équipe t'envoie, tes comptes rendus, et quels messages tu as lus.",
        "**Ambassadeur certifié** : si tu as ce titre, ton badge « Ambassadeur certifié ✓ » s'affiche, visible par tout le monde, sur ton profil et sur les fiches des lieux que tu as aidés, avec ton prénom (ou ton surnom) et, si tu en as indiqué une, ta structure : « Marie, pour l'asso Les Gourmands du 11e ». Il n'y a pas de liste publique des ambassadeurs certifiés. Si le titre t'est retiré, ou si tu supprimes ton compte, le badge disparaît.",
        "**Une note de l'équipe** : l'éditeur peut écrire une courte note privée sur ton compte (par exemple, pourquoi il l'a validé). Elle n'apparaît pas dans ton espace, mais tu peux la demander, comme tout le reste.",
        "**Tes connexions** : quand tu te connectes, ton navigateur reçoit une clé de connexion tirée au hasard, gardée dans un cookie (voir la page [Cookies](/cookies)). Notre serveur n'en garde que l'empreinte, avec l'heure de la connexion et celle de ta dernière activité : ni ton adresse IP, ni ton navigateur.",
        "**Les liens qu'on t'envoie par mail** : à l'inscription, un lien pour confirmer ton adresse e-mail ; et, si tu le demandes avec « Mot de passe oublié » (ou en nous écrivant), un lien pour choisir un nouveau mot de passe. Comme pour tes connexions, on ne garde que l'empreinte de ces liens, jamais les liens eux-mêmes, et chacun ne sert qu'une fois : l'empreinte du lien de confirmation est gardée **7 jours** au plus, et le lien de nouveau mot de passe ne marche que **24 heures**. Une fois ton adresse confirmée, on garde seulement la date de cette confirmation : l'équipe voit « e-mail vérifié » avant de valider ton compte. « Mot de passe oublié » répond la même chose, que l'adresse tapée ait un compte ou non : personne ne peut s'en servir pour savoir si tu es inscrit.",
        "**Tes propositions de modification d'une fiche de lieu** : si tu proposes de corriger une fiche (horaires, téléphone, infos pratiques…), on garde ce que tu proposes, ton « pourquoi », ce qu'il y avait avant sur la fiche, ton compte comme auteur, la décision de l'équipe et sa réponse, qu'on t'envoie par mail. L'équipe SOS Miam les voit, et les responsables du lieu (son gérant et son équipe, dans l'espace pro) aussi, mais sans ton nom ; ce qui est accepté devient la fiche du lieu, sans ton nom. Chaque proposition est effacée **1 an après la décision** ; si tu supprimes ton compte avant, elle reste sans lien vers toi jusqu'à cette date.",
        "**Ta date de naissance n'est pas gardée** : à l'inscription, elle sert seulement à vérifier que tu as 18 ans, puis elle est oubliée. Elle n'est ni enregistrée, ni écrite dans un journal. Si tu as moins de 18 ans, on ne garde rien du tout.",
        "**Pourquoi** : créer et faire vivre ton compte, vérifier les inscriptions (et que ton adresse e-mail est bien la tienne), t'envoyer un lien pour choisir un nouveau mot de passe quand tu le demandes, compter tes points, étudier tes candidatures (de fondateur, et savoir pour quelle ville ou quel département elle compte ; d'ambassadeur certifié, et montrer ton badge sur les fiches des lieux que tu aides) et les lieux que tu proposes, t'envoyer des missions et des messages, t'écrire par mail quand il le faut (bienvenue quand ton inscription est validée, des nouvelles du programme envoyées aux ambassadeurs, et un mois avant le retrait de ton rôle ou l'effacement de ton compte), et protéger ton compte.",
        "**Base légale** : pour ton compte, tes candidatures, ton titre d'ambassadeur certifié et les lieux que tu proposes, l'exécution des [conditions d'utilisation](/cgu#ambassadeurs) que tu acceptes en créant ton compte (article 6.1.b du RGPD). Pour la note de l'équipe et la sécurité (les limites d'essais, juste en dessous), l'intérêt légitime (article 6.1.f du RGPD) ; les intérêts poursuivis : bien suivre le programme, et empêcher quiconque de deviner ton mot de passe.",
        "**Les limites d'essais** : contre les robots, ton adresse IP sert à limiter le nombre de tentatives (par exemple 20 connexions toutes les 10 minutes, ou 10 inscriptions par heure). Elle reste seulement en mémoire, le temps de cette limite, et n'est jamais enregistrée. Après 5 mots de passe faux de suite pour une même adresse e-mail (ou, dans « Mon compte », pour ton compte), il faut aussi attendre avant chaque nouvel essai : 2 minutes, puis le double après chaque nouvel échec (2 heures au plus). L'adresse tapée (ou le numéro de ton compte) et le nombre d'échecs restent en mémoire, jamais sur le disque, et sont oubliés dès que le bon mot de passe est donné, ou au bout d'un jour.",
        "**« Déniché par »** : si un lieu que tu as proposé rejoint SOS Miam, ton prénom (ou ton surnom) peut s'afficher sur sa fiche, visible par tout le monde. Il y reste tel quel, même si tu le changes ensuite dans ton espace ou si ton compte est effacé, sauf si tu nous demandes de le changer ou de le retirer : un mail suffit.",
        `**Où et qui** : dans notre base de données, sur notre serveur loué à ${hebergeur.nom} et situé en France. Seul l'éditeur y a accès, depuis son logiciel de gestion. Nos mails partent de notre boîte bonjour@sosmiam.fr (voir « Qui voit tes données, et où elles sont ») ; le journal des envois (ton adresse, le type et l'objet du mail, la date, le résultat) est effacé au bout de 90 jours. Personne d'autre ne reçoit ces données : ni partenaire, ni lieu. Comme pour toute visite, ce que tu envoies passe par Cloudflare (voir « Cloudflare, qui protège le site »).`,
        "**Combien de temps** : tant que tu te sers de ton compte. **Après 1 an sans aucune visite dans ton espace**, ton rôle d'ambassadeur est retiré (avec tes missions, tes messages et ta candidature), mais ton compte reste, avec tes points et tes badges. **Après 2 ans sans connexion**, ton compte est effacé. Dans les deux cas, on te prévient par mail un mois avant. Si tu quittes le programme, ou si l'équipe t'en retire, c'est comme après 1 an sans visite : ton rôle part, ton compte reste. **Si ton inscription est refusée**, ton rôle d'ambassadeur (et ta demande) est retiré **30 jours** après le refus ; ton compte SOS Miam reste, pour l'app. **Une candidature de fondateur refusée**, comme **une candidature d'ambassadeur certifié refusée**, est effacée **3 mois** après notre réponse. Une connexion se ferme après **30 jours** sans visite, et au plus tard **90 jours** après avoir été ouverte. Un lien pour confirmer ton adresse e-mail marche **7 jours**, et un lien pour choisir un nouveau mot de passe **24 heures**, une seule fois chacun.",
        "**Si tu supprimes ton compte** : tout ce qui le concerne est effacé tout de suite (compte, points, badges, candidatures, titre d'ambassadeur certifié, missions, messages, connexions). Seuls restent les lieux que tu as proposés, dans nos demandes, sans plus aucun lien avec ton compte (et ton prénom « Déniché par » sur leur fiche, voir plus haut), et le journal des mails qu'on t'a envoyés (ton adresse, le type et l'objet du mail, la date, le résultat), effacé au plus tard 90 jours après chaque envoi. Dans tous les cas, une donnée effacée disparaît aussi de nos sauvegardes chiffrées au plus tard 30 jours après.",
        "**Obligatoire ?** Ton e-mail, un mot de passe, ton prénom ou ton surnom, ta ville et ta date de naissance sont nécessaires pour créer le compte ; le quartier est facultatif. Dans la candidature de fondateur, la commune où tu vis est nécessaire (elle dit pour quelle ville ou quel département tu candidates) ; tes réseaux et la façon dont tu as connu SOS Miam sont facultatifs. Dans la candidature d'ambassadeur certifié, tout est nécessaire, sauf le nom de ta structure ou de ton lieu.",
        "**Tes droits, en direct** : ton prénom, ta ville et ton quartier se changent dans « Mon compte », dans ton espace ; ton adresse e-mail, en nous écrivant. Tu peux aussi y **supprimer ton compte** (ton mot de passe t'est demandé), ou nous le demander par mail, depuis l'adresse de ton compte. Pour recevoir une copie de tes données, note de l'équipe comprise, écris-nous.",
      ],
    },
  ],
};
