// Lieux INVENTÉS pour montrer le principe avant le lancement (repris du prototype : /var/www/app mobile/app/data.js).
// Les noms sont fictifs ; quartiers, villes et spécialités sont réels. Remplacés par l'API au lancement.
// Les SOS de ce soir (Chez Nonna Lia, La Clé des Ruelles) sont des exemples.
import type { Lieu } from "@sos-miam/commun/types/lieu";
import { infosPratiquesExemples } from "~/contenus/infos-pratiques-exemples";

const lieuxSansInfosPratiques: Lieu[] = [
  {
    id: 0,
    nom: "Chez Nonna Lia",
    type: "resto",
    emoji: "🍝",
    quartier: "Écusson",
    ville: "Montpellier",
    position: { latitude: 43.611, longitude: 3.8767 },
    km: 0.35,
    prix: "€",
    prixMoyen: 16,
    info: "Trattoria",
    couleurs: ["#FF6B5B", "#C9184A"],
    texte: "Les pâtes fraîches de Lia, faites chaque matin. Ouvert depuis 3 mois, la salle a besoin de monde !",
    rescousses: 214,
    alerte: "Salle calme ce soir",
    sos: { places: 6, jusqua: "21:30", offre: "Un tiramisu offert" },
    horaires: "12h–14h30 · 19h–22h30",
    ouverture: [{ jours: [0,1,2,3,4,5,6], de: "12:00", a: "14:30" }, { jours: [0,1,2,3,4,5,6], de: "19:00", a: "22:30" }],
    plat: "Cacio e pepe · 12 €",
    tags: ["Fait maison", "Végé possible", "Terrasse"],
    envies: ["terrasse", "vege", "amoureux", "potes"],
    decouvertPar: "Léa",
    reservable: true,
  },
  {
    id: 1,
    nom: "Sucre & Garrigue",
    type: "patisserie",
    emoji: "🍬",
    quartier: "Comédie",
    ville: "Montpellier",
    position: { latitude: 43.6086, longitude: 3.88 },
    km: 0.6,
    prix: "€",
    prixMoyen: 6,
    info: "Confiserie artisanale",
    couleurs: ["#FFC94A", "#FB8500"],
    texte: "Des grisettes au miel de garrigue et à la réglisse, cuites dans un vieux chaudron en cuivre. Clémence a repris la recette de sa grand-mère.",
    rescousses: 87,
    alerte: "Fournée du soir à -30 %",
    horaires: "10h–19h30 · fermé lundi",
    ouverture: [{ jours: [0,2,3,4,5,6], de: "10:00", a: "19:30" }],
    plat: "Grisettes de Montpellier · 4,50 € le sachet",
    tags: ["Artisan", "Recette de famille", "À emporter"],
    envies: ["famille", "amoureux"],
    decouvertPar: "Inès",
    reservable: false,
  },
  {
    id: 2,
    nom: "La Figue Pressée",
    type: "bar",
    emoji: "🍹",
    quartier: "Figuerolles",
    ville: "Montpellier",
    position: { latitude: 43.6075, longitude: 3.864 },
    km: 1.1,
    prix: "€€",
    prixMoyen: 14,
    info: "Bar à cocktails",
    couleurs: ["#8F5CFF", "#3A86FF"],
    texte: "Cocktails maison à 8 € et un barman qui retient ton prénom. Le jeudi, c'est quiz sur la place !",
    rescousses: 56,
    alerte: "Happy hour jusqu'à 20h",
    horaires: "18h–1h · fermé dimanche et lundi",
    ouverture: [{ jours: [2,3,4,5,6], de: "18:00", a: "01:00" }],
    plat: "Spritz au Picpoul · 8 €",
    tags: ["Quiz le jeudi", "Happy hour"],
    envies: ["potes", "terrasse"],
    decouvertPar: "Hugo",
    reservable: false,
  },
  {
    id: 3,
    nom: "Les Baos de Mei",
    type: "resto",
    emoji: "🥟",
    quartier: "Boutonnet",
    ville: "Montpellier",
    position: { latitude: 43.6205, longitude: 3.872 },
    km: 1.4,
    prix: "€",
    prixMoyen: 12,
    info: "Street food taïwanaise",
    couleurs: ["#1FD1A5", "#118AB2"],
    texte: "Des baos moelleux et un thé au lait maison. Deux sœurs, une recette de famille et des prix d'étudiant.",
    rescousses: 132,
    horaires: "11h30–22h · fermé dimanche",
    ouverture: [{ jours: [1,2,3,4,5,6], de: "11:30", a: "22:00" }],
    plat: "Bao porc braisé · 6 €",
    tags: ["Recette de famille", "Rapide", "Végé possible"],
    envies: ["potes", "vege"],
    decouvertPar: "Hugo",
    reservable: false,
  },
  {
    id: 4,
    nom: "Le Chou Rieur",
    type: "patisserie",
    emoji: "🧁",
    quartier: "Beaux-Arts",
    ville: "Montpellier",
    position: { latitude: 43.617, longitude: 3.8835 },
    km: 1,
    prix: "€",
    prixMoyen: 7,
    info: "Choux à la crème",
    couleurs: ["#FF9DB5", "#FB6F92"],
    texte: "Des choux garnis à la minute et des parfums qui changent chaque semaine. Cette semaine : figue et miel de garrigue.",
    rescousses: 41,
    horaires: "10h–19h · fermé lundi",
    ouverture: [{ jours: [0,2,3,4,5,6], de: "10:00", a: "19:00" }],
    plat: "Chou praliné · 3 €",
    tags: ["Garni minute", "Sans gluten dispo"],
    envies: ["famille", "amoureux"],
    decouvertPar: "Inès",
    reservable: false,
  },
  {
    id: 5,
    nom: "Le Verre Tordu",
    type: "bar",
    emoji: "🍷",
    quartier: "Antigone",
    ville: "Montpellier",
    position: { latitude: 43.6085, longitude: 3.8895 },
    km: 1.3,
    prix: "€€",
    prixMoyen: 18,
    info: "Bar à vins nature",
    couleurs: ["#B5172B", "#6A040F"],
    texte: "Mimi choisit chaque bouteille chez de petits vignerons du Languedoc. Planches de pélardon à partager sous les arcades.",
    rescousses: 98,
    alerte: "Tables libres ce soir",
    horaires: "18h–minuit · fermé dimanche",
    ouverture: [{ jours: [1,2,3,4,5,6], de: "18:00", a: "00:00" }],
    plat: "Verre de Picpoul de Pinet · 5 €",
    tags: ["Vins nature", "Planches", "Terrasse"],
    envies: ["amoureux", "potes", "terrasse"],
    decouvertPar: "Karim",
    reservable: true,
  },
  {
    id: 6,
    nom: "Les Pagaies du Lez",
    type: "sortie",
    emoji: "🛶",
    quartier: "Port Marianne",
    ville: "Montpellier",
    position: { latitude: 43.6005, longitude: 3.8975 },
    km: 2.6,
    prix: "€€",
    prixMoyen: 15,
    info: "Kayak sur le Lez",
    couleurs: ["#4CC9F0", "#3A0CA3"],
    texte: "Une heure de kayak tranquille sur le Lez, entre les hérons et les immeubles de Port Marianne. Bastien prête les gilets et donne ses bonnes adresses.",
    rescousses: 64,
    alerte: "Balade au coucher du soleil",
    horaires: "10h–19h · mer., sam. et dim.",
    ouverture: [{ jours: [0,3,6], de: "10:00", a: "19:00" }],
    plat: "Balade d'1 h en kayak · 15 €",
    tags: ["Débutants bienvenus", "Gilets fournis"],
    envies: ["potes", "famille", "amoureux"],
    decouvertPar: "Tom",
    reservable: true,
  },
  {
    id: 7,
    nom: "La Clé des Ruelles",
    type: "sortie",
    emoji: "🗝️",
    quartier: "Saint-Roch",
    ville: "Montpellier",
    position: { latitude: 43.6045, longitude: 3.877 },
    km: 0.8,
    prix: "€€",
    prixMoyen: 22,
    info: "Escape game",
    couleurs: ["#FFB703", "#6A4C93"],
    texte: "Une heure pour retrouver le trésor caché d'un apothicaire de l'Écusson. Décor fait main par deux copains passionnés.",
    rescousses: 73,
    alerte: "Créneau libre à 20h",
    sos: { places: 4, jusqua: "22:00", offre: "Créneau de 20h à -20 %" },
    horaires: "14h–23h · fermé lundi",
    ouverture: [{ jours: [0,2,3,4,5,6], de: "14:00", a: "23:00" }],
    plat: "Partie de 60 min · 22 € par joueur",
    tags: ["2 à 6 joueurs", "Fait main"],
    envies: ["potes", "famille"],
    decouvertPar: "Tom",
    reservable: true,
  },
  {
    id: 8,
    nom: "Gadoue & Cie",
    type: "sortie",
    emoji: "🏺",
    quartier: "Arceaux",
    ville: "Montpellier",
    position: { latitude: 43.6105, longitude: 3.865 },
    km: 1.2,
    prix: "€€€",
    prixMoyen: 35,
    info: "Atelier poterie",
    couleurs: ["#E09F3E", "#9E2A2B"],
    texte: "Deux heures les mains dans l'argile, au pied de l'aqueduc des Arceaux. Tu repars avec ton bol (cuit la semaine d'après).",
    rescousses: 38,
    horaires: "Ateliers mer. 18h30, sam. et dim. 10h",
    ouverture: [{ jours: [3], de: "18:30", a: "20:30" }, { jours: [0,6], de: "10:00", a: "12:00" }],
    plat: "Atelier tournage 2 h · 35 €",
    tags: ["Petits groupes", "Débutants bienvenus"],
    envies: ["amoureux", "potes", "famille"],
    decouvertPar: "Sofia",
    reservable: true,
  },
  {
    id: 9,
    nom: "La Tielle de Pépita",
    type: "resto",
    emoji: "🐙",
    quartier: "Quartier Haut",
    ville: "Sète",
    position: { latitude: 43.404, longitude: 3.693 },
    km: 33,
    prix: "€",
    prixMoyen: 11,
    info: "Tielles & poulpe",
    couleurs: ["#F77F00", "#D62828"],
    texte: "La tielle sétoise comme chez Pépita : pâte dorée, poulpe à la tomate bien relevé. Petite salle avec vue sur les toits du Quartier Haut.",
    rescousses: 121,
    alerte: "Salle calme ce soir",
    horaires: "11h30–14h30 · 18h30–22h · fermé dim. soir et lundi",
    ouverture: [{ jours: [0,2,3,4,5,6], de: "11:30", a: "14:30" }, { jours: [2,3,4,5,6], de: "18:30", a: "22:00" }],
    plat: "Tielle sétoise · 4 € la part",
    tags: ["Spécialité sétoise", "À emporter"],
    envies: ["potes", "famille"],
    decouvertPar: "Max",
    reservable: true,
  },
  {
    id: 10,
    nom: "Les Zézettes de Ginette",
    type: "patisserie",
    emoji: "🍪",
    quartier: "Le Canal",
    ville: "Sète",
    position: { latitude: 43.4005, longitude: 3.696 },
    km: 34,
    prix: "€",
    prixMoyen: 6,
    info: "Biscuiterie",
    couleurs: ["#FFD166", "#EF476F"],
    texte: "Les zézettes de Sète, ces biscuits croquants au vin blanc, cuits par fournées de 200 au bord du canal. Ginette fait goûter tout le monde.",
    rescousses: 66,
    horaires: "9h–19h · fermé mardi",
    ouverture: [{ jours: [0,1,3,4,5,6], de: "09:00", a: "19:00" }],
    plat: "Sachet de zézettes · 5 €",
    tags: ["Artisan", "Spécialité sétoise"],
    envies: ["famille"],
    decouvertPar: "Max",
    reservable: false,
  },
  {
    id: 11,
    nom: "Aux Pâtés de Lucette",
    type: "patisserie",
    emoji: "🥧",
    quartier: "Centre historique",
    ville: "Pézenas",
    position: { latitude: 43.4595, longitude: 3.423 },
    km: 52,
    prix: "€",
    prixMoyen: 5,
    info: "Petits pâtés",
    couleurs: ["#E9C46A", "#BC6C25"],
    texte: "Le petit pâté de Pézenas, sucré-salé et en forme de bobine, comme au temps de Molière. Lucette en façonne 300 chaque matin.",
    rescousses: 47,
    horaires: "8h–13h · 15h–19h · fermé dim. après-midi et lundi",
    ouverture: [{ jours: [0,2,3,4,5,6], de: "08:00", a: "13:00" }, { jours: [2,3,4,5,6], de: "15:00", a: "19:00" }],
    plat: "Petit pâté de Pézenas · 2,80 €",
    tags: ["Recette historique", "À emporter"],
    envies: ["famille"],
    decouvertPar: "Léa",
    reservable: false,
  },
  {
    id: 12,
    nom: "Paddle & Flamants",
    type: "sortie",
    emoji: "🏄",
    quartier: "Rive gauche",
    ville: "Palavas-les-Flots",
    position: { latitude: 43.529, longitude: 3.929 },
    km: 12,
    prix: "€€",
    prixMoyen: 20,
    info: "Paddle sur les étangs",
    couleurs: ["#00B4D8", "#F72585"],
    texte: "Balade en paddle sur l'étang, au milieu des flamants roses. Initiation offerte aux grands débutants, combinaisons prêtées.",
    rescousses: 52,
    horaires: "9h30–18h30 · du mer. au dim.",
    ouverture: [{ jours: [0,3,4,5,6], de: "09:30", a: "18:30" }],
    plat: "Balade guidée 1 h 30 · 20 €",
    tags: ["Flamants roses", "Débutants bienvenus"],
    envies: ["amoureux", "potes", "famille"],
    decouvertPar: "Sofia",
    reservable: true,
  },
  {
    id: 13,
    nom: "La Cabane d'Émile",
    type: "resto",
    emoji: "🦪",
    quartier: "Bord de l'étang",
    ville: "Bouzigues",
    position: { latitude: 43.448, longitude: 3.658 },
    km: 28,
    prix: "€€",
    prixMoyen: 22,
    info: "Dégustation d'huîtres",
    couleurs: ["#90E0EF", "#0077B6"],
    texte: "Émile élève ses huîtres de Bouzigues à cent mètres de la table. Dégustation les pieds presque dans l'étang de Thau.",
    rescousses: 109,
    horaires: "11h–15h · le soir du jeu. au sam. · fermé lundi",
    ouverture: [{ jours: [0,2,3,4,5,6], de: "11:00", a: "15:00" }, { jours: [4,5,6], de: "18:00", a: "21:30" }],
    plat: "6 huîtres de Bouzigues · 10 €",
    tags: ["Producteur", "Vue sur l'étang"],
    envies: ["amoureux", "terrasse", "potes"],
    decouvertPar: "Karim",
    reservable: true,
  },
  {
    id: 14,
    nom: "Tapas & Féria",
    type: "bar",
    emoji: "💃",
    quartier: "Allées Paul-Riquet",
    ville: "Béziers",
    position: { latitude: 43.3415, longitude: 3.216 },
    km: 70,
    prix: "€€",
    prixMoyen: 16,
    info: "Bar à tapas",
    couleurs: ["#E63946", "#FFB703"],
    texte: "Planches de tapas, Faugères au verre et guitare flamenca en live. L'esprit de la Féria toute l'année, à deux pas des allées.",
    rescousses: 58,
    alerte: "Concert flamenco ce soir",
    horaires: "18h–1h · du mer. au sam.",
    ouverture: [{ jours: [3,4,5,6], de: "18:00", a: "01:00" }],
    plat: "Planche de tapas + verre de Faugères · 14 €",
    tags: ["Concerts", "Tapas"],
    envies: ["potes", "terrasse"],
    decouvertPar: "Karim",
    reservable: true,
  },
  {
    id: 15,
    nom: "Les Oreillettes de Bernadette",
    type: "patisserie",
    emoji: "🍩",
    quartier: "Village médiéval",
    ville: "Saint-Guilhem-le-Désert",
    position: { latitude: 43.734, longitude: 3.549 },
    km: 41,
    prix: "€",
    prixMoyen: 7,
    info: "Salon de thé",
    couleurs: ["#FFAFCC", "#CDB4DB"],
    texte: "Des oreillettes à la fleur d'oranger, fines comme de la dentelle, servies avec un chocolat chaud dans une ruelle du village médiéval.",
    rescousses: 0,
    horaires: "10h–18h · fermé mardi",
    ouverture: [{ jours: [0,1,3,4,5,6], de: "10:00", a: "18:00" }],
    plat: "Assiette d'oreillettes · 4,50 €",
    tags: ["Fait maison", "Ruelle au calme"],
    envies: ["famille", "amoureux", "vege"],
    nouveau: true,
    reservable: false,
  },
  {
    id: 16,
    nom: "Les Toqués de la Lergue",
    type: "resto",
    emoji: "🧀",
    quartier: "Bord de la Lergue",
    ville: "Lodève",
    position: { latitude: 43.7315, longitude: 3.319 },
    km: 55,
    prix: "€€",
    prixMoyen: 24,
    info: "Bistrot de terroir",
    couleurs: ["#83C5BE", "#006D77"],
    texte: "Un jeune couple de cuisiniers revenu au pays : produits du Larzac et pélardon rôti. Menu du jour à 17 €.",
    rescousses: 0,
    horaires: "12h–14h · 19h30–21h30 · fermé dim. soir et lundi",
    ouverture: [{ jours: [0,2,3,4,5,6], de: "12:00", a: "14:00" }, { jours: [2,3,4,5,6], de: "19:30", a: "21:30" }],
    plat: "Pélardon rôti au miel · 9 €",
    tags: ["Produits locaux", "Menu du jour"],
    envies: ["amoureux", "vege", "terrasse"],
    nouveau: true,
    reservable: true,
  },
  {
    id: 17,
    nom: "Les Copains du Muscat",
    type: "bar",
    emoji: "🍇",
    quartier: "Cœur de ville",
    ville: "Lunel",
    position: { latitude: 43.6745, longitude: 4.1355 },
    km: 25,
    prix: "€",
    prixMoyen: 12,
    info: "Bar à vins & tapas",
    couleurs: ["#C77DFF", "#7B2CBF"],
    texte: "Muscat de Lunel au verre, tapas de la Petite Camargue et soirées bouvine. Trois copains d'enfance derrière le comptoir.",
    rescousses: 0,
    horaires: "17h–minuit · du mer. au dim.",
    ouverture: [{ jours: [0,3,4,5,6], de: "17:00", a: "00:00" }],
    plat: "Verre de muscat de Lunel · 4 €",
    tags: ["Muscat", "Terrasse", "Soirées bouvine"],
    envies: ["potes", "terrasse"],
    nouveau: true,
    reservable: false,
  },
];

/** Les lieux d'exemple, avec leurs infos pratiques (téléphone de fiction, animaux, accès, paiements…) */
export const lieuxExemples: Lieu[] = lieuxSansInfosPratiques.map((lieu) => ({ ...lieu, pratique: infosPratiquesExemples[lieu.id] }));
