// Publications d'EXEMPLE du fil « Pour toi » : une par lieu d'exemple, plus 3 de créateurs.
// Médias : vidéos et photos libres de Mixkit (licence gratuite, usage commercial permis, sans crédit obligatoire),
// recadrées et compressées dans assets/medias-demo (sources : assets/medias-demo/SOURCES.md). J'aime et commentaires inventés.
// Toutes marquées « illustration » : l'app affiche « Vidéo / Photos d'illustration » pour ne pas faire croire qu'elles viennent du lieu.
// « partenariat » : le lieu a offert ou payé → mention « Collaboration commerciale » (obligatoire, voir la FAQ).
import type { Publication } from "~/contenus/type-publication";

export const publicationsExemples: Publication[] = [
  {
    id: "lieu-0",
    lieuId: 0,
    auteur: { type: "lieu" },
    legende: "Les pâtes du jour sortent tout juste de la machine 🍝 Ce soir, la salle a de la place : viens goûter la cacio e pepe de Lia !",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-0.mp4"), affiche: require("../../assets/medias-demo/lieu-0-affiche.jpg") },
    jaimes: 1240,
    illustration: true,
    commentaires: 86,
  },
  {
    id: "lieu-1",
    lieuId: 1,
    auteur: { type: "lieu" },
    legende: "La fournée de grisettes du jour : miel de garrigue et réglisse, cuites dans le chaudron de mamie. -30 % sur la fournée du soir !",
    media: { type: "photos", photos: [require("../../assets/medias-demo/lieu-1-1.jpg"), require("../../assets/medias-demo/lieu-1-2.jpg"), require("../../assets/medias-demo/lieu-1-3.jpg")] },
    jaimes: 612,
    illustration: true,
    commentaires: 34,
  },
  {
    id: "lieu-2",
    lieuId: 2,
    auteur: { type: "lieu" },
    legende: "Ce soir, le spritz au Picpoul est à 8 € et le quiz commence à 21h. Ramène tes potes 🍹",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-2.mp4"), affiche: require("../../assets/medias-demo/lieu-2-affiche.jpg") },
    jaimes: 980,
    illustration: true,
    commentaires: 57,
  },
  {
    id: "lieu-3",
    lieuId: 3,
    auteur: { type: "lieu" },
    legende: "Nos baos sortent du panier vapeur toutes les dix minutes 🥟 Et le thé au lait est fait maison.",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-3.mp4"), affiche: require("../../assets/medias-demo/lieu-3-affiche.jpg") },
    jaimes: 1530,
    illustration: true,
    commentaires: 112,
  },
  {
    id: "lieu-4",
    lieuId: 4,
    auteur: { type: "lieu" },
    legende: "Des choux garnis à la minute : croustillants dehors, fondants dedans. Version sans gluten disponible !",
    media: { type: "photos", photos: [require("../../assets/medias-demo/lieu-4-1.jpg"), require("../../assets/medias-demo/lieu-4-2.jpg"), require("../../assets/medias-demo/lieu-4-3.jpg")] },
    jaimes: 870,
    illustration: true,
    commentaires: 41,
  },
  {
    id: "lieu-5",
    lieuId: 5,
    auteur: { type: "lieu" },
    legende: "Vins nature, planches du marché, et des tables libres ce soir 🍷",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-5.mp4"), affiche: require("../../assets/medias-demo/lieu-5-affiche.jpg") },
    jaimes: 455,
    illustration: true,
    commentaires: 22,
  },
  {
    id: "lieu-6",
    lieuId: 6,
    auteur: { type: "lieu" },
    legende: "La balade au coucher du soleil sur le Lez, c'est ce soir. Débutants bienvenus, gilets fournis 🛶",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-6.mp4"), affiche: require("../../assets/medias-demo/lieu-6-affiche.jpg") },
    jaimes: 2100,
    illustration: true,
    commentaires: 143,
  },
  {
    id: "lieu-7",
    lieuId: 7,
    auteur: { type: "lieu" },
    legende: "Il vous reste 60 minutes pour sortir des ruelles… Un créneau vient de se libérer à 20h 🗝️",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-7.mp4"), affiche: require("../../assets/medias-demo/lieu-7-affiche.jpg") },
    jaimes: 760,
    illustration: true,
    commentaires: 48,
  },
  {
    id: "lieu-8",
    lieuId: 8,
    auteur: { type: "lieu" },
    legende: "Tes mains, un peu de terre et un tour : ton premier bol t'attend 🏺",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-8.mp4"), affiche: require("../../assets/medias-demo/lieu-8-affiche.jpg") },
    jaimes: 1340,
    illustration: true,
    commentaires: 77,
  },
  {
    id: "lieu-9",
    lieuId: 9,
    auteur: { type: "lieu" },
    legende: "La tielle de Pépita, recette sétoise au poulpe, à emporter ou à déguster face au port 🐙",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-9.mp4"), affiche: require("../../assets/medias-demo/lieu-9-affiche.jpg") },
    jaimes: 690,
    illustration: true,
    commentaires: 39,
  },
  {
    id: "lieu-10",
    lieuId: 10,
    auteur: { type: "lieu" },
    legende: "Les zézettes de Ginette, croquantes comme il faut. Recette sétoise, fournée du matin.",
    media: { type: "photos", photos: [require("../../assets/medias-demo/lieu-10-1.jpg"), require("../../assets/medias-demo/lieu-10-2.jpg"), require("../../assets/medias-demo/lieu-10-3.jpg")] },
    jaimes: 520,
    illustration: true,
    commentaires: 25,
  },
  {
    id: "lieu-11",
    lieuId: 11,
    auteur: { type: "lieu" },
    legende: "Les petits pâtés de Pézenas, sucrés-salés, d'après une recette historique de la ville 🥧",
    media: { type: "photos", photos: [require("../../assets/medias-demo/lieu-11-1.jpg"), require("../../assets/medias-demo/lieu-11-2.jpg"), require("../../assets/medias-demo/lieu-11-3.jpg")] },
    jaimes: 380,
    illustration: true,
    commentaires: 19,
  },
  {
    id: "lieu-12",
    lieuId: 12,
    auteur: { type: "lieu" },
    legende: "Du paddle au milieu des flamants roses, à vingt minutes de Montpellier 🦩",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-12.mp4"), affiche: require("../../assets/medias-demo/lieu-12-affiche.jpg") },
    jaimes: 1610,
    illustration: true,
    commentaires: 95,
  },
  {
    id: "lieu-13",
    lieuId: 13,
    auteur: { type: "lieu" },
    legende: "Huîtres de Bouzigues ouvertes devant toi, avec vue sur l'étang de Thau 🦪",
    media: { type: "photos", photos: [require("../../assets/medias-demo/lieu-13-1.jpg"), require("../../assets/medias-demo/lieu-13-2.jpg"), require("../../assets/medias-demo/lieu-13-3.jpg")] },
    jaimes: 1120,
    illustration: true,
    commentaires: 64,
  },
  {
    id: "lieu-14",
    lieuId: 14,
    auteur: { type: "lieu" },
    legende: "Concert flamenco ce soir et tapas jusqu'à minuit 💃",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-14.mp4"), affiche: require("../../assets/medias-demo/lieu-14-affiche.jpg") },
    jaimes: 840,
    illustration: true,
    commentaires: 51,
  },
  {
    id: "lieu-15",
    lieuId: 15,
    auteur: { type: "lieu" },
    legende: "Les oreillettes de Bernadette, fines et sucrées, dans une ruelle au calme de Saint-Guilhem.",
    media: { type: "photos", photos: [require("../../assets/medias-demo/lieu-15-1.jpg"), require("../../assets/medias-demo/lieu-15-2.jpg"), require("../../assets/medias-demo/lieu-15-3.jpg")] },
    jaimes: 310,
    illustration: true,
    commentaires: 12,
  },
  {
    id: "lieu-16",
    lieuId: 16,
    auteur: { type: "lieu" },
    legende: "Le menu du jour suit le marché de Lodève : ce qui pousse ici finit dans ton assiette 🥕",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-16.mp4"), affiche: require("../../assets/medias-demo/lieu-16-affiche.jpg") },
    jaimes: 260,
    illustration: true,
    commentaires: 9,
  },
  {
    id: "lieu-17",
    lieuId: 17,
    auteur: { type: "lieu" },
    legende: "Un muscat bien frais en terrasse, entre copains : c'est ça, la belle vie 🥂",
    media: { type: "video", video: require("../../assets/medias-demo/lieu-17.mp4"), affiche: require("../../assets/medias-demo/lieu-17-affiche.jpg") },
    jaimes: 405,
    illustration: true,
    commentaires: 18,
  },
  {
    id: "createur-1",
    lieuId: 0,
    auteur: { type: "createur", pseudo: "lea.mange", partenariat: "Repas offert" },
    legende: "J'ai testé la trattoria de Lia : pâtes fraîches du matin et tiramisu maison. Franchement ? J'y retourne la semaine prochaine 😍",
    media: { type: "video", video: require("../../assets/medias-demo/createur-1.mp4"), affiche: require("../../assets/medias-demo/createur-1-affiche.jpg") },
    jaimes: 3400,
    illustration: true,
    commentaires: 210,
  },
  {
    id: "createur-2",
    lieuId: 13,
    auteur: { type: "createur", pseudo: "sete.gourmand" },
    legende: "Les huîtres de l'étang, ouvertes sous mes yeux. Une pépite absolue 🦪",
    media: { type: "video", video: require("../../assets/medias-demo/createur-2.mp4"), affiche: require("../../assets/medias-demo/createur-2-affiche.jpg") },
    jaimes: 2780,
    illustration: true,
    commentaires: 154,
  },
  {
    id: "createur-3",
    lieuId: 7,
    auteur: { type: "createur", pseudo: "max.sort", partenariat: "Partie offerte" },
    legende: "On s'en est sortis avec 4 minutes d'avance 😅 Le meilleur escape game de l'Écusson !",
    media: { type: "video", video: require("../../assets/medias-demo/createur-3.mp4"), affiche: require("../../assets/medias-demo/createur-3-affiche.jpg") },
    jaimes: 1900,
    illustration: true,
    commentaires: 98,
  },
];
